

HOST = "localhost"
DATABASE = "naurillion-test1"
DB_PORT = "5432"
DB_USERNAME = "postgres"
DB_PASSWORD = "admin"
JWT_SECRET = "testing"



HOST=139.59.7.248
DATABASE=naurilliontest1
DB_PORT=5432
DB_USERNAME=postgres
DB_PASSWORD=Oracle_1
JWT_SALTROUNDS = 10




SUPER_ADMIN_EMAIL = "naurillion@test.ae"

SERVER_PORT= 5000
SERVER_ENCRYPTION_KEY = "0d899cbc312a10"
VERIFICATION_TOKEN_SIZE = 6
BASE_URL= "http://localhost:5000/"
# BASE_URL= "http://139.59.7.248:5000/"
SERVER_URL = "http://localhost:3000/"
# SERVER_URL = "http://139.59.81.236:3000/"
BLOCKCHAIN_SERVER_URL = "http://139.59.7.248:3000"
# BLOCKCHAIN_SERVER_URL = "http://localhost:3005"
  
MAILTRAP_HOST="smtp.mailtrap.io"
MAILTRAP_PORT= 2525
MAILTRAP_AUTH_USER= "05d430279edc46"
MAILTRAP_AUTH_PASS= "1415099af5b6e5"
MAILTRAP_FROM_EMAIL= "noreply@naurillion.com"

NEXMO_API_KEY = "b0458e44"
NEXMO_API_SECRET= "TEcikSe9fIedijaZ"
NEXMO_PHONE_NO="971523541300"

PAYPAY_CLIENT_ID= 'AS3BHtjRmXz3qcUc4Eal6K9sPanBlCSt4N-hn5ITritBOKDUsG5czdoAwrOz5E37YYpZtTQrUG2otPZ_'
PAYPAL_CLIENT_SECRET = 'EMxYirWO28aNMOy-nXjkSDn5YRgSYCSBzIq3Pgie39fLVp7bvsFO1e-ew0eHL_zKoqR6j0Wlui2DuoyE'

TWILIO_ACCOUNTSID="ACe7c37a5c03c9cddf3faff8e906e58aa0"
TWILIO_AUTHTOKEN="09e1b24b215b5027ed908cfca457bd2b"
TWILIO_SERVICEID="VA497517a9dae83fb93b5157727940b237"
