module.exports = [
  {
    name: "pkr-currency",
    currency: "PKR",
    price: 0,
    unit: "USD",
    type: "liquid",
    total_supply: 0,
    remaining_supply: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "aud-currency",
    currency: "AUD",
    price: 0,
    unit: "USD",
    type: "liquid",
    total_supply: 0,
    remaining_supply: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "inr-currency",
    currency: "INR",
    price: 0,
    unit: "USD",
    type: "liquid",
    total_supply: 0,
    remaining_supply: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
